ALTER TABLE posts DROP COLUMN IF EXISTS title_en;
ALTER TABLE posts DROP COLUMN IF EXISTS content_en;
ALTER TABLE posts DROP COLUMN IF EXISTS excerpt_en;
ALTER TABLE posts DROP COLUMN IF EXISTS slug_en;
ALTER TABLE posts DROP COLUMN IF EXISTS is_document;
ALTER TABLE posts DROP COLUMN IF EXISTS pdf_media_id;

ALTER TABLE categories DROP COLUMN IF EXISTS name_en;
ALTER TABLE categories DROP COLUMN IF EXISTS slug_en;
ALTER TABLE categories DROP COLUMN IF EXISTS description_en;
ALTER TABLE categories DROP COLUMN IF EXISTS parent_id;
