ALTER TABLE "media"
ADD COLUMN IF NOT EXISTS "type" VARCHAR(20) NOT NULL DEFAULT 'image',
ADD COLUMN IF NOT EXISTS "duration" INT,
ADD COLUMN IF NOT EXISTS "resolution" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "file_size" BIGINT,
ADD COLUMN IF NOT EXISTS "mime_type" VARCHAR(100);
