// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/posts/:slug": {
    params: {
      "slug": string;
    };
  };
  "/feedback": {
    params: {};
  };
  "/authors": {
    params: {};
  };
  "/authors/:nickname": {
    params: {
      "nickname": string;
    };
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/system/login": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/feedbacks": {
    params: {};
  };
  "/admin/media": {
    params: {};
  };
  "/admin/categories": {
    params: {};
  };
  "/admin/tags": {
    params: {};
  };
  "/admin/comments": {
    params: {};
  };
  "/admin/translate-jobs": {
    params: {};
  };
  "/admin/chat-logs": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/audit-logs": {
    params: {};
  };
  "/admin/posts": {
    params: {};
  };
  "/admin/posts/new": {
    params: {};
  };
  "/admin/posts/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/posts/:slug" | "/feedback" | "/authors" | "/authors/:nickname" | "/forgot-password" | "/reset-password" | "/system/login" | "/admin" | "/admin/feedbacks" | "/admin/media" | "/admin/categories" | "/admin/tags" | "/admin/comments" | "/admin/translate-jobs" | "/admin/chat-logs" | "/admin/settings" | "/admin/users" | "/admin/audit-logs" | "/admin/posts" | "/admin/posts/new" | "/admin/posts/edit/:id" | "/*";
  };
  "layouts/RootLayout.tsx": {
    id: "root-layout";
    page: "/" | "/posts/:slug" | "/feedback" | "/authors" | "/authors/:nickname" | "/forgot-password" | "/reset-password" | "/system/login" | "/admin" | "/admin/feedbacks" | "/admin/media" | "/admin/categories" | "/admin/tags" | "/admin/comments" | "/admin/translate-jobs" | "/admin/chat-logs" | "/admin/settings" | "/admin/users" | "/admin/audit-logs" | "/admin/posts" | "/admin/posts/new" | "/admin/posts/edit/:id" | "/*";
  };
  "layouts/PublicLayout.tsx": {
    id: "layouts/PublicLayout";
    page: "/" | "/posts/:slug" | "/feedback" | "/authors" | "/authors/:nickname";
  };
  "pages/BlogHome.tsx": {
    id: "pages/BlogHome";
    page: "/";
  };
  "pages/BlogPostDetail.tsx": {
    id: "pages/BlogPostDetail";
    page: "/posts/:slug";
  };
  "pages/FeedbackNew.tsx": {
    id: "pages/FeedbackNew";
    page: "/feedback";
  };
  "pages/AuthorsList.tsx": {
    id: "pages/AuthorsList";
    page: "/authors";
  };
  "pages/AuthorDetail.tsx": {
    id: "pages/AuthorDetail";
    page: "/authors/:nickname";
  };
  "pages/ForgotPassword.tsx": {
    id: "pages/ForgotPassword";
    page: "/forgot-password";
  };
  "pages/ResetPassword.tsx": {
    id: "pages/ResetPassword";
    page: "/reset-password";
  };
  "pages/Login.tsx": {
    id: "pages/Login";
    page: "/system/login";
  };
  "components/ProtectedRoute.tsx": {
    id: "components/ProtectedRoute";
    page: "/admin" | "/admin/feedbacks" | "/admin/media" | "/admin/categories" | "/admin/tags" | "/admin/comments" | "/admin/translate-jobs" | "/admin/chat-logs" | "/admin/settings" | "/admin/users" | "/admin/audit-logs" | "/admin/posts" | "/admin/posts/new" | "/admin/posts/edit/:id";
  };
  "layouts/AdminLayout.tsx": {
    id: "layouts/AdminLayout";
    page: "/admin" | "/admin/feedbacks" | "/admin/media" | "/admin/categories" | "/admin/tags" | "/admin/comments" | "/admin/translate-jobs" | "/admin/chat-logs" | "/admin/settings" | "/admin/users" | "/admin/audit-logs" | "/admin/posts" | "/admin/posts/new" | "/admin/posts/edit/:id";
  };
  "pages/Dashboard.tsx": {
    id: "pages/Dashboard";
    page: "/admin";
  };
  "pages/FeedbacksAdmin.tsx": {
    id: "pages/FeedbacksAdmin";
    page: "/admin/feedbacks";
  };
  "pages/MediaLibrary.tsx": {
    id: "pages/MediaLibrary";
    page: "/admin/media";
  };
  "pages/Categories.tsx": {
    id: "pages/Categories";
    page: "/admin/categories";
  };
  "pages/Tags.tsx": {
    id: "pages/Tags";
    page: "/admin/tags";
  };
  "pages/CommentModeration.tsx": {
    id: "pages/CommentModeration";
    page: "/admin/comments";
  };
  "pages/TranslateJobs.tsx": {
    id: "pages/TranslateJobs";
    page: "/admin/translate-jobs";
  };
  "pages/ChatLogsAdmin.tsx": {
    id: "pages/ChatLogsAdmin";
    page: "/admin/chat-logs";
  };
  "pages/Settings.tsx": {
    id: "pages/Settings";
    page: "/admin/settings";
  };
  "pages/Users.tsx": {
    id: "pages/Users";
    page: "/admin/users";
  };
  "pages/AuditLog.tsx": {
    id: "pages/AuditLog";
    page: "/admin/audit-logs";
  };
  "pages/PostList.tsx": {
    id: "pages/PostList";
    page: "/admin/posts";
  };
  "pages/PostEditor.tsx": {
    id: "post-new";
    page: "/admin/posts/new";
  } | {
    id: "post-edit";
    page: "/admin/posts/edit/:id";
  };
  "pages/NotFound.tsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "root-layout": typeof import("./src/layouts/RootLayout.tsx");
  "layouts/PublicLayout": typeof import("./src/layouts/PublicLayout.tsx");
  "pages/BlogHome": typeof import("./src/pages/BlogHome.tsx");
  "pages/BlogPostDetail": typeof import("./src/pages/BlogPostDetail.tsx");
  "pages/FeedbackNew": typeof import("./src/pages/FeedbackNew.tsx");
  "pages/AuthorsList": typeof import("./src/pages/AuthorsList.tsx");
  "pages/AuthorDetail": typeof import("./src/pages/AuthorDetail.tsx");
  "pages/ForgotPassword": typeof import("./src/pages/ForgotPassword.tsx");
  "pages/ResetPassword": typeof import("./src/pages/ResetPassword.tsx");
  "pages/Login": typeof import("./src/pages/Login.tsx");
  "components/ProtectedRoute": typeof import("./src/components/ProtectedRoute.tsx");
  "layouts/AdminLayout": typeof import("./src/layouts/AdminLayout.tsx");
  "pages/Dashboard": typeof import("./src/pages/Dashboard.tsx");
  "pages/FeedbacksAdmin": typeof import("./src/pages/FeedbacksAdmin.tsx");
  "pages/MediaLibrary": typeof import("./src/pages/MediaLibrary.tsx");
  "pages/Categories": typeof import("./src/pages/Categories.tsx");
  "pages/Tags": typeof import("./src/pages/Tags.tsx");
  "pages/CommentModeration": typeof import("./src/pages/CommentModeration.tsx");
  "pages/TranslateJobs": typeof import("./src/pages/TranslateJobs.tsx");
  "pages/ChatLogsAdmin": typeof import("./src/pages/ChatLogsAdmin.tsx");
  "pages/Settings": typeof import("./src/pages/Settings.tsx");
  "pages/Users": typeof import("./src/pages/Users.tsx");
  "pages/AuditLog": typeof import("./src/pages/AuditLog.tsx");
  "pages/PostList": typeof import("./src/pages/PostList.tsx");
  "post-new": typeof import("./src/pages/PostEditor.tsx");
  "post-edit": typeof import("./src/pages/PostEditor.tsx");
  "pages/NotFound": typeof import("./src/pages/NotFound.tsx");
};